import {Graph,TYPES} from './graph.js';
import {makePreview} from './mesh.js';
const $=s=>document.querySelector(s),graphEl=$('#graph'),paletteEl=$('#palette'),varsEl=$('#variables');
for(const [type,label] of [['box','▣ Box'],['cylinder','◉ Cylinder'],['sphere','● Sphere'],['number','# Number'],['float','0.0 Float'],['integer','123 Integer'],['string','Aa String'],['vector3','◆ Vector3'],['velocity','↝ Velocity'],['add','＋ Add'],['multiply','× Multiply'],['transform','↗ Transform'],['output','◈ Model Output']]){const b=document.createElement('button');b.className=`palette ${TYPES[type].cat}`;b.dataset.type=type;b.textContent=label;paletteEl.appendChild(b)}
let selected=null;const draw=makePreview($('#preview'));const graph=new Graph(graphEl,(n,w,node)=>{if(node)selected=node;sync()});
function input(node,key,seen=new Set()){const w=graph.wires.find(x=>x.to.node===node.id&&x.to.key===key);if(!w)return node.values[key];if(seen.has(node.id))return node.values[key];const next=new Set(seen);next.add(node.id);const s=graph.getNode(w.from.node);if(!s)return node.values[key];if(['number','float','integer','string','vector3','velocity'].includes(s.type))return s.values.value;if(s.type==='add')return Number(input(s,'a',next)||0)+Number(input(s,'b',next)||0);if(s.type==='multiply')return Number(input(s,'a',next)||0)*Number(input(s,'b',next)||0);return build(s,next)}
function build(n,seen=new Set()){if(!n)return null;if(n.type==='box')return{type:'box',width:Number(input(n,'width',seen)??2),height:Number(input(n,'height',seen)??2),depth:Number(input(n,'depth',seen)??2),position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]};if(n.type==='sphere'){const r=Number(input(n,'radius',seen)??1);return{type:'sphere',radius:r,segments:Number(input(n,'segments',seen)??24),position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]}}if(n.type==='cylinder')return{type:'cylinder',radius:Number(input(n,'radius',seen)??1),height:Number(input(n,'height',seen)??2),segments:Number(input(n,'segments',seen)??24),position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]};if(n.type==='transform'){const w=graph.wires.find(x=>x.to.node===n.id&&x.to.key==='mesh');if(!w)return null;const m=build(graph.getNode(w.from.node),new Set(seen));const v=k=>{const x=input(n,k,new Set(seen));return Array.isArray(x)?x:[0,0,0]};return m?{...m,position:v('position'),rotation:v('rotation'),scale:v('scale')}:null}return null}
function evaluate(){const o=graph.nodes.find(n=>n.type==='output'),w=o&&graph.wires.find(x=>x.to.node===o.id&&x.to.key==='mesh');if(w)return build(graph.getNode(w.from.node));const n=[...graph.nodes].reverse().find(x=>['box','sphere','cylinder','transform'].includes(x.type));return build(n)}
function sync(){try{const m=evaluate();draw(m);$('#modelInfo').textContent=m?m.type[0].toUpperCase()+m.type.slice(1):'No model';$('#status').textContent='Live';$('#inspector').innerHTML=selected?`<strong>${TYPES[selected.type].title}</strong><div class="line"><span>Kind</span><code>${TYPES[selected.type].kind}</code></div>`:'Select a block'}catch(e){console.error(e);$('#status').textContent='Error'}}
paletteEl.addEventListener('click',e=>{const b=e.target.closest('.palette');if(!b)return;selected=graph.add(b.dataset.type,graphEl.clientWidth/2-100-graph.offset.x,graphEl.clientHeight/2-60-graph.offset.y);sync()});$('#runBtn').onclick=()=>sync();$('#resetBtn').onclick=()=>location.reload();window.addEventListener('resize',()=>{draw();graph.render()});
const box=graph.add('box',100,130),transform=graph.add('transform',420,150),output=graph.add('output',750,170);graph.connect({node:box.id,key:'mesh'},{node:transform.id,key:'mesh'});graph.connect({node:transform.id,key:'mesh'},{node:output.id,key:'mesh'});selected=box;sync();
