export const TYPES={
 box:{title:'Box',kind:'Mesh',cat:'mesh',inputs:[['width','Width','float',2],['height','Height','float',2],['depth','Depth','float',2]],outputs:[['mesh','Mesh','mesh']]},
 sphere:{title:'Sphere',kind:'Mesh',cat:'mesh',inputs:[['radius','Radius','float',1],['segments','Segments','integer',24]],outputs:[['mesh','Mesh','mesh']]},
 cylinder:{title:'Cylinder',kind:'Mesh',cat:'mesh',inputs:[['radius','Radius','float',1],['height','Height','float',2],['segments','Segments','integer',24]],outputs:[['mesh','Mesh','mesh']]},
 number:{title:'Number',kind:'Value',cat:'data',inputs:[],outputs:[['value','Value','number']]},
 float:{title:'Float',kind:'Value',cat:'data',inputs:[],outputs:[['value','Value','float']]},
 integer:{title:'Integer',kind:'Value',cat:'data',inputs:[],outputs:[['value','Value','integer']]},
 string:{title:'String',kind:'Value',cat:'data',inputs:[],outputs:[['value','Text','string']]},
 vector3:{title:'Vector 3',kind:'Value',cat:'data',inputs:[],outputs:[['value','Vector','vector3']]},
 velocity:{title:'Velocity',kind:'Physics',cat:'data',inputs:[['value','Velocity','vector3',[0,0,0]]],outputs:[['velocity','Velocity','velocity']]},
 add:{title:'Add',kind:'Math',cat:'math',inputs:[['a','A','number',2],['b','B','number',3]],outputs:[['result','Result','number']]},
 multiply:{title:'Multiply',kind:'Math',cat:'math',inputs:[['a','A','number',2],['b','B','number',3]],outputs:[['result','Result','number']]},
 transform:{title:'Transform',kind:'Transform',cat:'transform',inputs:[['mesh','Mesh','mesh'],['position','Position','vector3',[0,0,0]],['rotation','Rotation','vector3',[0,0,0]],['scale','Scale','vector3',[1,1,1]]],outputs:[['mesh','Mesh','mesh']]},
 output:{title:'Model Output',kind:'Output',cat:'output',inputs:[['mesh','Model','mesh']],outputs:[]}
};
const clone=v=>Array.isArray(v)?v.slice():v;
export class Graph{
 constructor(el,onChange){this.el=el;this.onChange=onChange;this.nodes=[];this.wires=[];this.offset={x:0,y:0};this.drag=null;this.connecting=null;this.menu=document.querySelector('#contextMenu');this.bind();this.bindAddButton()}
 bind(){
  this.el.addEventListener('pointerdown',e=>{if(e.target!==this.el)return;this.hideMenu();this.el.setPointerCapture?.(e.pointerId);this.drag={x:e.clientX,y:e.clientY,ox:this.offset.x,oy:this.offset.y}});
  this.el.addEventListener('pointermove',e=>{if(!this.drag)return;this.offset.x=this.drag.ox+e.clientX-this.drag.x;this.offset.y=this.drag.oy+e.clientY-this.drag.y;this.render()});
  const stop=()=>{if(this.drag){this.drag=null;this.onChange?.(this.nodes,this.wires)}};this.el.addEventListener('pointerup',stop);this.el.addEventListener('pointercancel',stop);
  this.el.addEventListener('dblclick',e=>{if(e.target.closest('.node'))return;e.preventDefault();const r=this.el.getBoundingClientRect();this.showMenu(e.clientX,e.clientY,e.clientX-r.left,e.clientY-r.top)});
  this.el.addEventListener('contextmenu',e=>e.preventDefault());
  document.addEventListener('pointerdown',e=>{if(!e.target.closest('.context-menu')&&!e.target.closest('#addBtn'))this.hideMenu()});
 }
 bindAddButton(){const btn=document.querySelector('#addBtn');if(!btn)return;btn.addEventListener('click',e=>{e.stopPropagation();const r=this.el.getBoundingClientRect();const x=Math.min(this.el.clientWidth-245,Math.max(250,this.el.clientWidth*.5));const y=70;this.showMenu(r.left+x,r.top+y,x,y)})}
 showMenu(cx,cy,gx,gy){if(!this.menu)return;const groups={mesh:[],data:[],math:[],transform:[],output:[]};for(const [id,d] of Object.entries(TYPES))groups[d.cat]?.push([id,d]);const groupHtml=Object.entries(groups).map(([cat,list])=>list.length?`<div class="menu-section">${cat}</div>${list.map(([id,d])=>`<button class="menu-item create-code" data-type="${id}"><span><i class="type-dot ${cat}"></i>${d.title}</span><span class="menu-arrow">${d.kind}</span></button>`).join('')}`:'').join('');this.menu.innerHTML=groupHtml;const r=this.el.getBoundingClientRect();this.menu.style.left=Math.max(4,Math.min(cx-r.left,this.el.clientWidth-245))+'px';this.menu.style.top=Math.max(4,Math.min(cy-r.top,this.el.clientHeight-260))+'px';this.menu.hidden=false;this.menu.querySelectorAll('.create-code').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();this.add(b.dataset.type,gx-this.offset.x,gy-this.offset.y);this.hideMenu()}))}
 hideMenu(){if(this.menu)this.menu.hidden=true}
 add(type,x=120,y=100){const def=TYPES[type];if(!def)return;const values={};for(const [key,,typeName,defaultValue] of def.inputs)values[key]=clone(defaultValue??(typeName==='string'?'':0));if(type==='number'||type==='float'||type==='integer')values.value=1;if(type==='string')values.value='Hello';if(type==='vector3')values.value=[0,0,0];const node={id:globalThis.crypto?.randomUUID?.()||`n_${Date.now()}_${Math.random().toString(36).slice(2)}`,type,x,y,values};this.nodes.push(node);this.render();this.onChange?.(this.nodes,this.wires);return node}
 getNode(id){return this.nodes.find(n=>n.id===id)}
 getPort(id,dir,key){const n=this.getNode(id);return (TYPES[n?.type]?.[dir==='input'?'inputs':'outputs']||[]).find(p=>p[0]===key)}
 compatible(a,b){return a===b||a==='any'||b==='any'||(a==='integer'&&(b==='number'||b==='float'))||(b==='integer'&&(a==='number'||a==='float'))||(a==='number'&&b==='float')||(a==='float'&&b==='number')}
 connect(from,to){const out=this.getPort(from.node,'output',from.key),inn=this.getPort(to.node,'input',to.key);if(!out||!inn||from.node===to.node||!this.compatible(out[2],inn[2]))return false;this.wires=this.wires.filter(w=>!(w.to.node===to.node&&w.to.key===to.key));this.wires.push({from:{node:from.node,key:from.key},to:{node:to.node,key:to.key}});this.render();this.onChange?.(this.nodes,this.wires);return true}
 render(){this.el.innerHTML='<svg class="wires"></svg>';for(const n of this.nodes)this.renderNode(n);this.renderWires()}
 renderNode(n){const def=TYPES[n.type];if(!def)return;const d=document.createElement('div');d.className='node';d.dataset.id=n.id;d.style.left=`${n.x+this.offset.x}px`;d.style.top=`${n.y+this.offset.y}px`;d.innerHTML=`<div class="node-head"><span>${def.title}</span><span class="node-kind">${def.kind}</span></div><div class="node-body">${this.rows(n,def)}</div>`;
  d.addEventListener('pointerdown',e=>{e.stopPropagation();if(e.target.closest('.port')||e.target.closest('.value'))return;const sx=e.clientX,sy=e.clientY,ox=n.x,oy=n.y;d.setPointerCapture?.(e.pointerId);const move=q=>{n.x=ox+q.clientX-sx;n.y=oy+q.clientY-sy;this.render()};const up=()=>{d.removeEventListener('pointermove',move);d.removeEventListener('pointerup',up);d.removeEventListener('pointercancel',up);this.onChange?.(this.nodes,this.wires)};d.addEventListener('pointermove',move);d.addEventListener('pointerup',up);d.addEventListener('pointercancel',up)});
  d.addEventListener('click',()=>{this.el.querySelectorAll('.node').forEach(x=>x.classList.remove('selected'));d.classList.add('selected');this.onChange?.(this.nodes,this.wires,n)});this.el.appendChild(d);
  d.querySelectorAll('.value').forEach(input=>input.addEventListener('input',()=>{if(input.dataset.vector){n.values[input.dataset.key][+input.dataset.vector]=Number(input.value)||0}else if(input.type==='number')n.values[input.dataset.key]=Number(input.value)||0;else n.values[input.dataset.key]=input.value;this.onChange?.(this.nodes,this.wires,n)}));
  d.querySelectorAll('.port').forEach(p=>p.addEventListener('pointerdown',e=>this.startConnection(e,n.id,p.dataset.dir,p.dataset.key)));
 }
 rows(n,def){return def.inputs.map(([key,label,type,defaultValue])=>{const connected=this.wires.some(w=>w.to.node===n.id&&w.to.key===key);let editor='';if(connected)editor='<span class="connected-value">connected</span>';else if(type==='vector3')editor=`<span class="vec-inputs">${[0,1,2].map(i=>`<input class="value" type="number" step="0.1" data-key="${key}" data-vector="${i}" value="${n.values[key]?.[i]??0}">`).join('')}</span>`;else if(type==='string')editor=`<input class="value" data-key="${key}" value="${String(n.values[key]??'')}">`;else editor=`<input class="value" type="number" step="${type==='integer'?'1':'0.1'}" data-key="${key}" value="${n.values[key]??defaultValue??0}">`;return `<div class="row"><i class="port input-port type-${type}" data-dir="input" data-key="${key}"></i><span class="row-label">${label}</span><span class="type-badge">${type}</span>${editor}</div>`}).concat(def.outputs.map(([key,label,type])=>`<div class="row"><span class="row-label">${label}</span><span class="type-badge">${type}</span><i class="port output-port type-${type}" data-dir="output" data-key="${key}"></i></div>`)).join('')||'<div class="empty">No inputs or outputs</div>'}
 startConnection(e,node,dir,key){e.stopPropagation();if(dir!=='output')return;const start=this.portPoint(node,key,'output');if(!start)return;this.connecting={node,key,start};const svg=this.el.querySelector('.wires');const temp=document.createElementNS('http://www.w3.org/2000/svg','path');temp.classList.add('wire-preview');svg.appendChild(temp);const move=q=>{const r=this.el.getBoundingClientRect();temp.setAttribute('d',this.curve(start.x,start.y,q.clientX-r.left,q.clientY-r.top))};const up=q=>{document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',up);const target=document.elementFromPoint(q.clientX,q.clientY)?.closest('.input-port');if(target){const nd=target.closest('.node');if(nd)this.connect({node,key},{node:nd.dataset.id,key:target.dataset.key})}temp.remove();this.connecting=null};document.addEventListener('pointermove',move);document.addEventListener('pointerup',up)}
 portPoint(node,key,dir){const p=this.el.querySelector(`.node[data-id="${node}"] .port[data-dir="${dir}"][data-key="${key}"]`);if(!p)return null;const a=p.getBoundingClientRect(),b=this.el.getBoundingClientRect();return{x:a.left+a.width/2-b.left,y:a.top+a.height/2-b.top}}
 curve(x1,y1,x2,y2){const c=Math.max(35,Math.abs(x2-x1)*.5);return `M ${x1} ${y1} C ${x1+c} ${y1}, ${x2-c} ${y2}, ${x2} ${y2}`}
 renderWires(){const svg=this.el.querySelector('.wires');for(const w of this.wires){const a=this.portPoint(w.from.node,w.from.key,'output'),b=this.portPoint(w.to.node,w.to.key,'input');if(!a||!b)continue;const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.classList.add('wire');p.setAttribute('d',this.curve(a.x,a.y,b.x,b.y));svg.appendChild(p)}}
}