class FBXImporter{constructor(editor,scene,ui){this.editor=editor;this.scene=scene;this.ui=ui}
parseNumbers(text){return(text.match(/[-+]?(?:\d+\.?\d*|\.\d+)(?:[eE][-+]?\d+)?/g)||[]).map(Number)}
extractASCIIArray(text,label){const re=new RegExp(label+'\\s*:\\s*\\*\\d+\\s*\\{\\s*a\\s*:\\s*([\\s\\S]*?)\\}','i');const m=text.match(re);return m?this.parseNumbers(m[1]):[]}
parseASCII(text,name){const nums=this.extractASCIIArray(text,'Vertices'),idx=this.extractASCIIArray(text,'PolygonVertexIndex');if(!nums.length||!idx.length)throw new Error('No readable ASCII mesh geometry was found.');const vertices=[];for(let i=0;i+2<nums.length;i+=3)vertices.push([nums[i],nums[i+1],nums[i+2]]);const faces=[],face=[];for(const raw of idx){const i=raw<0?-raw-1:raw;if(i>=0&&i<vertices.length)face.push(i);if(raw<0){if(face.length>=3)faces.push(face.splice(0));else face.length=0}}return{name,geometry:{vertices,faces:faces.filter(f=>f.length>=3)}}}
async inflate(bytes){if(typeof DecompressionStream==='undefined')throw new Error('This browser cannot decompress compressed binary FBX arrays.');try{const stream=new Blob([bytes]).stream().pipeThrough(new DecompressionStream('deflate'));return new Uint8Array(await new Response(stream).arrayBuffer())}catch(e){throw new Error('Could not decompress a compressed FBX array. Try exporting the FBX with compression disabled.')}}
parseBinaryHeader(buf){const bytes=new Uint8Array(buf,0,23),sig='Kaydara FBX Binary  ';for(let i=0;i<sig.length;i++)if(bytes[i]!==sig.charCodeAt(i))throw new Error('Not a valid binary FBX file.');return new DataView(buf).getUint32(23,true)}
async parseBinary(buf,name){const version=this.parseBinaryHeader(buf),view=new DataView(buf),state={pos:27,version,readOffset(v,wide){const p=this.pos;this.pos+=wide?8:4;return wide?Number(v.getBigUint64(p,true)):v.getUint32(p,true)},readBytes(v,n){const p=this.pos;this.pos+=n;return new Uint8Array(v.buffer,v.byteOffset+p,n)}};const root=await this.readNodes(view,state,view.byteLength);const geometries=[];const walk=n=>{if(n.name==='Geometry'){const verts=n.children.find(x=>x.name==='Vertices')?.value,idx=n.children.find(x=>x.name==='PolygonVertexIndex')?.value;if(Array.isArray(verts)&&Array.isArray(idx)){const vertices=[];for(let i=0;i+2<verts.length;i+=3)vertices.push([verts[i],verts[i+1],verts[i+2]]);const faces=[],face=[];for(const raw of idx){const i=raw<0?-raw-1:raw;if(i>=0&&i<vertices.length)face.push(i);if(raw<0){if(face.length>=3)faces.push(face.splice(0));else face.length=0}}if(vertices.length&&faces.length)geometries.push({name:this.cleanName(n.props&&n.props[1])||name,geometry:{vertices,faces}})}}for(const c of n.children)walk(c)};for(const n of root)walk(n);if(!geometries.length)throw new Error('Binary FBX contains no readable mesh geometry.');return geometries}
async readArray(view,state,type){const len=state.readOffset(view,false),encoding=state.readOffset(view,false),compressedLength=state.readOffset(view,false);const size=type==='d'||type==='l'?8:type==='f'||type==='i'?4:1;let bytes;if(encoding===0)bytes=state.readBytes(view,len*size);else bytes=await this.inflate(state.readBytes(view,compressedLength));if(bytes.byteLength<len*size)throw new Error('FBX array data is incomplete.');const dv=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),out=[];for(let i=0;i<len;i++){const p=i*size;if(type==='d')out.push(dv.getFloat64(p,true));else if(type==='f')out.push(dv.getFloat32(p,true));else if(type==='i')out.push(dv.getInt32(p,true));else if(type==='l')out.push(Number(dv.getBigInt64(p,true)));else out.push(dv.getUint8(p)!==0)}return out}
async readProperty(view,state){const t=String.fromCharCode(view.getUint8(state.pos++));if(t==='Y'){const v=view.getInt16(state.pos,true);state.pos+=2;return v}if(t==='C')return view.getUint8(state.pos++)!==0;if(t==='I'){const v=view.getInt32(state.pos,true);state.pos+=4;return v}if(t==='F'){const v=view.getFloat32(state.pos,true);state.pos+=4;return v}if(t==='D'){const v=view.getFloat64(state.pos,true);state.pos+=8;return v}if(t==='L'){const v=Number(view.getBigInt64(state.pos,true));state.pos+=8;return v}if(t==='S'||t==='R'){const len=view.getUint32(state.pos,true);state.pos+=4;const bytes=new Uint8Array(view.buffer,view.byteOffset+state.pos,len);state.pos+=len;return t==='R'?bytes.slice():new TextDecoder().decode(bytes)}if('dfilb'.includes(t.toLowerCase()))return this.readArray(view,state,t.toLowerCase());throw new Error('Unsupported FBX property type: '+t)}
async readNode(view,state){const wide=state.version>=7500,header=wide?25:13;if(state.pos+header>view.byteLength)return null;const start=state.pos,end=state.readOffset(view,wide),propCount=state.readOffset(view,wide),propLen=state.readOffset(view,wide),nameLen=view.getUint8(state.pos++);const nullSize=wide?25:13;if(!end){state.pos=Math.min(view.byteLength,start+nullSize);return null}if(end<=start||end>view.byteLength){state.pos=Math.min(view.byteLength,start+header+nameLen+propLen);return null}const nb=new Uint8Array(view.buffer,view.byteOffset+state.pos,nameLen);state.pos+=nameLen;const name=new TextDecoder().decode(nb),propStart=state.pos,props=[];while(state.pos<propStart+propLen){if(props.length>=propCount)break;props.push(await this.readProperty(view,state))}state.pos=propStart+propLen;const children=[];while(state.pos<end){const before=state.pos,n=await this.readNode(view,state);if(n)children.push(n);if(state.pos<=before){state.pos=Math.min(end,before+nullSize);break}}state.pos=end;return{name,props,children,value:props[0]}}
async readNodes(view,state,end){const out=[],nullSize=state.version>=7500?25:13;while(state.pos+nullSize<=end){const start=state.pos,off=state.version>=7500?Number(view.getBigUint64(state.pos,true)):view.getUint32(state.pos,true);if(off===0){state.pos=Math.min(end,start+nullSize);break}const n=await this.readNode(view,state);if(n)out.push(n);else if(state.pos<=start)state.pos=start+nullSize}return out}
cleanName(v){return typeof v==='string'?v.replace(/\x00.*$/,'').replace(/^Geometry::|^Model::/,'').trim():''}
centerGeometry(g){if(!g.vertices.length)return;const min=[Infinity,Infinity,Infinity],max=[-Infinity,-Infinity,-Infinity];for(const v of g.vertices)for(let a=0;a<3;a++){if(v[a]<min[a])min[a]=v[a];if(v[a]>max[a])max[a]=v[a]}const c=min.map((v,i)=>(v+max[i])*.5);for(const v of g.vertices){v[0]-=c[0];v[1]-=c[1];v[2]-=c[2]}}
async importFile(file){const buf=await file.arrayBuffer(),probe=new TextDecoder().decode(new Uint8Array(buf,0,Math.min(buf.byteLength,27)));let data;if(probe.startsWith('Kaydara FBX Binary'))data=await this.parseBinary(buf,file.name.replace(/\.fbx$/i,''));else{const text=new TextDecoder().decode(buf);data=[this.parseASCII(text,file.name.replace(/\.fbx$/i,''))]}for(const item of data){this.centerGeometry(item.geometry);const o={name:item.name||'FBX Mesh',geometry:item.geometry,position:[0,0,0],rotation:[0,0,0],scale:[1,1,1]};this.scene.objects.push(o);this.editor.selectObject(o);this.editor.mode='object';this.editor.setTool('select')}this.ui&&this.ui.refresh();return data}}
window.FBXImporter=FBXImporter;