const RemoteApp=(()=>{
'use strict';
const $=id=>document.getElementById(id);let peer=null,conn=null,call=null,role=null,hostStream=null,inputEnabled=false;
const setStatus=(e,t,c='')=>{e.textContent=t;e.className='status '+c};
const setBadge=(t,ok=false)=>{$('connectionBadge').textContent='● '+t;$('connectionBadge').classList.toggle('ok',ok)};
const setInput=()=>{$('inputBadge').textContent='Input: '+(inputEnabled?'enabled':'disabled');$('toggleInput').textContent=inputEnabled?'Disable input':'Enable input'};
const setRole=r=>{role=r;$('roleBadge').textContent='Role: '+(r?r[0].toUpperCase()+r.slice(1):'None');document.body.dataset.role=r||''};
const roomId=()=> 'ikirumi-remote-'+Math.random().toString(36).slice(2,8).toUpperCase();
function cleanup(){try{conn?.close()}catch{}try{call?.close()}catch{}try{peer?.destroy()}catch{}conn=null;call=null;peer=null}
function showStream(s){$('remoteVideo').srcObject=s;$('remoteVideo').hidden=false;$('screenEmpty').hidden=true}
function hostEvent(d){if(!d||!inputEnabled)return;const x=Math.max(0,Math.min(1,+d.x||0)),y=Math.max(0,Math.min(1,+d.y||0)),cx=innerWidth*x,cy=innerHeight*y,target=document.elementFromPoint(cx,cy)||document.body,o={bubbles:true,cancelable:true,clientX:cx,clientY:cy,button:d.button||0,buttons:d.buttons||0};if(['pointermove','mousedown','mouseup'].includes(d.type))target.dispatchEvent(new PointerEvent(d.type,{...o,pointerType:'mouse',isPrimary:true}));if(['mousedown','mouseup','click'].includes(d.type))target.dispatchEvent(new MouseEvent(d.type,o));if(d.type==='keydown'||d.type==='keyup')(document.activeElement||document.body).dispatchEvent(new KeyboardEvent(d.type,{bubbles:true,cancelable:true,key:d.key,code:d.code,ctrlKey:!!d.ctrl,altKey:!!d.alt,shiftKey:!!d.shift,metaKey:!!d.meta,repeat:!!d.repeat}))}
function hostConnection(c){conn=c;c.on('open',()=>{inputEnabled=true;setInput();setStatus($('hostStatus'),'Controller connected. Remote input is active.','ok');setBadge('Controller connected',true);if(hostStream)call=peer.call(c.peer,hostStream)});c.on('data',hostEvent);c.on('close',()=>{inputEnabled=false;setInput();setStatus($('hostStatus'),'Controller disconnected.','');setBadge('Host waiting',true)})}
async function startHost(){setRole('host');$('startHost').disabled=true;$('stopHost').disabled=false;$('roomCode').textContent='...';peer=new Peer(roomId());peer.on('open',id=>{$('roomCode').textContent=id.slice(-6);setStatus($('hostStatus'),'Host ready. Share the room code.','ok');setBadge('Host waiting',true)});peer.on('connection',hostConnection);peer.on('error',e=>setStatus($('hostStatus'),'Connection error: '+e.type,'bad'));try{hostStream=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:30},audio:false});$('localVideo').srcObject=hostStream;$('localVideo').hidden=false;$('hostEmpty').hidden=true;hostStream.getVideoTracks()[0].addEventListener('ended',stopHost);if(conn?.open)call=peer.call(conn.peer,hostStream)}catch{setStatus($('hostStatus'),'Screen sharing was cancelled or blocked.','bad')}}
function stopHost(){cleanup();hostStream?.getTracks().forEach(t=>t.stop());hostStream=null;$('startHost').disabled=false;$('stopHost').disabled=true;$('roomCode').textContent='------';$('localVideo').hidden=true;$('localVideo').srcObject=null;$('hostEmpty').hidden=false;inputEnabled=false;setInput();setRole(null);setBadge('Offline');setStatus($('hostStatus'),'Host stopped.','')}
function connectController(){const code=$('roomInput').value.trim().toUpperCase();if(code.length!==6)return setStatus($('controllerStatus'),'Enter the six-character room code.','bad');setRole('controller');$('connect').disabled=true;$('disconnect').disabled=false;peer=new Peer();peer.on('open',()=>{conn=peer.connect('ikirumi-remote-'+code,{reliable:true});conn.on('open',()=>{setStatus($('controllerStatus'),'Connected. Waiting for screen...','ok');setBadge('Controller connected',true);$('toggleInput').disabled=false});conn.on('close',()=>{setStatus($('controllerStatus'),'Disconnected.','');setBadge('Offline');$('toggleInput').disabled=true})});peer.on('call',incoming=>{call=incoming;incoming.on('stream',showStream);incoming.answer()});peer.on('error',e=>{setStatus($('controllerStatus'),'Connection error: '+e.type,'bad');$('connect').disabled=false;$('disconnect').disabled=true})}
function disconnect(){cleanup();$('connect').disabled=false;$('disconnect').disabled=true;$('toggleInput').disabled=true;inputEnabled=false;setInput();$('remoteVideo').hidden=true;$('remoteVideo').srcObject=null;$('screenEmpty').hidden=false;setRole(null);setBadge('Offline')}
function send(d){if(role==='controller'&&inputEnabled&&conn?.open)conn.send(d)}
function pointer(e,type){const r=$('remoteVideo').getBoundingClientRect();if(r.width&&r.height)send({type,x:(e.clientX-r.left)/r.width,y:(e.clientY-r.top)/r.height,button:e.button||0,buttons:e.buttons||0})}
$('remoteVideo').addEventListener('mousemove',e=>pointer(e,'pointermove'));$('remoteVideo').addEventListener('mousedown',e=>{e.preventDefault();pointer(e,'mousedown')});$('remoteVideo').addEventListener('mouseup',e=>{e.preventDefault();pointer(e,'mouseup')});$('remoteVideo').addEventListener('click',e=>{e.preventDefault();pointer(e,'click')});$('remoteVideo').addEventListener('contextmenu',e=>e.preventDefault());
window.addEventListener('keydown',e=>{if(role==='controller'&&inputEnabled)send({type:'keydown',key:e.key,code:e.code,ctrl:e.ctrlKey,alt:e.altKey,shift:e.shiftKey,meta:e.metaKey,repeat:e.repeat})});window.addEventListener('keyup',e=>{if(role==='controller'&&inputEnabled)send({type:'keyup',key:e.key,code:e.code,ctrl:e.ctrlKey,alt:e.altKey,shift:e.shiftKey,meta:e.metaKey})});
$('startHost').onclick=startHost;$('stopHost').onclick=stopHost;$('connect').onclick=connectController;$('disconnect').onclick=disconnect;$('toggleInput').onclick=()=>{inputEnabled=!inputEnabled;setInput()};$('fullscreen').onclick=()=>$('screen').requestFullscreen?.();$('copyCode').onclick=async()=>{try{await navigator.clipboard.writeText($('roomCode').textContent);$('copyCode').textContent='Copied';setTimeout(()=>$('copyCode').textContent='Copy code',1000)}catch{}};$('roomInput').oninput=e=>e.target.value=e.target.value.replace(/[^a-z0-9]/gi,'').toUpperCase().slice(0,6);setInput();
})();