const BlueprintEngine=(()=>{
const TYPES=['number','string','boolean','any','array'];
function cast(v,t){if(t==='any')return v;if(t==='string')return String(v);if(t==='number'){const n=Number(v);if(Number.isNaN(n))throw Error('Cannot convert value to number');return n}if(t==='boolean'){if(typeof v==='boolean')return v;const s=String(v).trim().toLowerCase();if(s==='true'||s==='1')return true;if(s==='false'||s==='0'||s==='')return false;throw Error('Cannot convert value to boolean')}if(t==='array'){if(Array.isArray(v))return v;try{const a=JSON.parse(v);if(Array.isArray(a))return a}catch{}throw Error('Cannot convert value to array')}return v}
function splitArgs(s){let a=[],v='',q=false,d=0;for(let i=0;i<s.length;i++){let c=s[i];if(c==='"'&&s[i-1]!=='\\')q=!q;if(!q&&(c==='('||c==='['))d++;if(!q&&(c===')'||c===']'))d--;if(c===','&&!q&&!d){a.push(v.trim());v=''}else v+=c}if(v.trim()||s.endsWith(','))a.push(v.trim());return a}
function expr(s,vars,inputs){s=s.trim();if(!s)return null;let env={Math,Number,String,Boolean,Array,JSON,PI:Math.PI,true:true,false:false};Object.keys(vars).forEach(k=>env[k]=vars[k].value);Object.keys(inputs).forEach(k=>env[k]=inputs[k]);env.toNumber=v=>cast(v,'number');env.toString=v=>cast(v,'string');env.toBoolean=v=>cast(v,'boolean');env.toArray=v=>cast(v,'array');env.length=v=>v?.length??0;env.abs=Math.abs;env.min=Math.min;env.max=Math.max;env.round=Math.round;env.floor=Math.floor;env.ceil=Math.ceil;env.sqrt=Math.sqrt;env.pow=Math.pow;env.random=Math.random;env.clamp=(v,a,b)=>Math.min(b,Math.max(a,v));env.contains=(a,v)=>a?.includes(v)??false;env.startsWith=(a,v)=>String(a).startsWith(v);env.endsWith=(a,v)=>String(a).endsWith(v);env.upper=v=>String(v).toUpperCase();env.lower=v=>String(v).toLowerCase();env.concat=(a,b)=>String(a)+String(b);const names=Object.keys(env);const vals=names.map(k=>env[k]);try{return Function(...names,'return ('+s+');')(...vals)}catch(e){throw Error('Expression error: '+e.message)}}
function parse(code){const raw=code.replace(/\r/g,'').split('\n'),lines=[];let errors=[];raw.forEach((line,i)=>{let t=line.trim();if(!t||t.startsWith('//'))return;lines.push({n:i+1,t})});return {lines,errors}}
async function run(code,inputValues,onEvent,signal){const p=parse(code);let vars={},inputs={},outputs=[],pc=0;const get=()=>({vars,inputs,outputs});for(const l of p.lines){let m=l.t.match(/^input\s+([A-Za-z_$][\w$]*)(?:\s*:\s*(number|string|boolean|any|array))?(?:\s*=\s*(.*))?$/i);if(m){let v=m[3]?expr(m[3],vars,inputs):'';inputs[m[1]]=v;onEvent?.({type:'input',name:m[1],dataType:(m[2]||'string').toLowerCase(),value:v});continue}m=l.t.match(/^var\s+([A-Za-z_$][\w$]*)(?:\s*:\s*(number|string|boolean|any|array))?\s*=\s*(.*)$/i);if(m){let typ=(m[2]||'any').toLowerCase();vars[m[1]]={type:typ,value:cast(expr(m[3],vars,inputs),typ)};continue}m=l.t.match(/^const\s+([A-Za-z_$][\w$]*)(?:\s*:\s*(number|string|boolean|any|array))?\s*=\s*(.*)$/i);if(m){let typ=(m[2]||'any').toLowerCase();vars[m[1]]={type:typ,value:cast(expr(m[3],vars,inputs),typ),constant:true};continue}}
async function execRange(start,end){let i=start;while(i<end){if(signal?.aborted)throw Error('Execution stopped');let t=p.lines[i].t,m;if((m=t.match(/^delay\s+(.+)$/i))){let ms=Math.max(0,Number(expr(m[1],vars,inputs)));onEvent?.({type:'delay',ms});await new Promise((res,rej)=>{let id=setTimeout(res,Math.min(ms,60000));signal?.addEventListener('abort',()=>{clearTimeout(id);rej(Error('Execution stopped'))},{once:true})});i++;continue}m=t.match(/^set\s+([A-Za-z_$][\w$]*)\s*=\s*(.*)$/i);if(m){if(!vars[m[1]])throw Error('Line '+p.lines[i].n+': unknown variable '+m[1]);if(vars[m[1]].constant)throw Error('Line '+p.lines[i].n+': constant cannot be changed');vars[m[1]].value=cast(expr(m[2],vars,inputs),vars[m[1]].type);onEvent?.({type:'var'});i++;continue}m=t.match(/^output(?:\s+(.+))?$/i);if(m){let v=m[1]?expr(m[1],vars,inputs):'';outputs.push(v);onEvent?.({type:'output',value:v});i++;continue}m=t.match(/^print\s+(.+)$/i);if(m){let v=expr(m[1],vars,inputs);outputs.push(v);onEvent?.({type:'output',value:v});i++;continue}m=t.match(/^if\s+(.+)\s+then$/i);if(m){let depth=1,j=i+1,elseAt=-1;for(;j<end;j++){if(/^if\s+.+\s+then$/i.test(p.lines[j].t))depth++;if(/^end$/i.test(p.lines[j].t))depth--;if(depth===1&&/^else$/i.test(p.lines[j].t))elseAt=j;if(depth===0)break}if(depth!==0)throw Error('Line '+p.lines[i].n+': missing end');if(expr(m[1],vars,inputs))await execRange(i+1,elseAt>0?elseAt:j);else if(elseAt>0)await execRange(elseAt+1,j);i=j+1;continue}m=t.match(/^repeat\s+(.+)\s+times$/i);if(m){let depth=1,j=i+1;for(;j<end;j++){if(/^repeat\s+.+\s+times$/i.test(p.lines[j].t))depth++;if(/^end$/i.test(p.lines[j].t))depth--;if(depth===0)break}if(depth!==0)throw Error('Line '+p.lines[i].n+': missing end');let n=Math.floor(Number(expr(m[1],vars,inputs)));if(n<0||n>100000)throw Error('Line '+p.lines[i].n+': repeat count must be 0–100000');for(let k=0;k<n;k++)await execRange(i+1,j);i=j+1;continue}if(/^end$|^else$/i.test(t)){i++;continue}if(/^log\s+(.+)$/i.test(t)){outputs.push(expr(t.replace(/^log\s+/i,''),vars,inputs));i++;continue}if(/^(var|const|input)\b/i.test(t)){i++;continue}throw Error('Line '+p.lines[i].n+': unknown instruction');}}
await execRange(0,p.lines.length);onEvent?.({type:'done',state:get()});return get()}
return {run,TYPES,cast,expr,parse};
})();