const PythonEngine=(()=>{
let pyodide=null,loading=null,controller=null;
async function load(){if(pyodide)return pyodide;if(loading)return loading;loading=(async()=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/pyodide/v0.27.7/full/pyodide.js';document.head.appendChild(s);await new Promise((resolve,reject)=>{s.onload=resolve;s.onerror=()=>reject(Error('Could not load Python runtime'))});pyodide=await loadPyodide();return pyodide})();return loading}
function safeJson(value){try{return JSON.stringify(value,(k,v)=>{if(typeof v==='function')return '[function]';if(v instanceof Error)return String(v);return v})}catch{return JSON.stringify(String(value))}}
function makeCode(code,inputValues){const values={...inputValues};let pre='import asyncio\nimport math\nimport random\nimport json\nimport time\n\n';for(const [k,v] of Object.entries(values)){if(!/^[A-Za-z_]\w*$/.test(k))continue;pre+=k+' = '+safeJson(v)+'\n';}pre+='\nasync def delay(milliseconds):\n    await asyncio.sleep(max(0, float(milliseconds)) / 1000)\n\n';const lines=code.replace(/\r/g,'').split('\n');const body=lines.map(x=>x.trim()? '    '+x:'').join('\n');return pre+'async def __main__():\n'+(body||'    pass')+'\n    return {k: v for k, v in locals().items() if not k.startswith("__")}\n\n__bp_result = await __main__()\njson.dumps(__bp_result, default=str)'}
function jsValue(v){if(v===null||v===undefined)return v;if(typeof v.toJs==='function'){try{return v.toJs({dict_converter:Object.fromEntries})}catch{try{return v.toJs()}catch{return String(v)}}}return v}
async function run(code,inputValues,onEvent,signal){controller=new AbortController();const p=await load();if(signal){if(signal.aborted)throw Error('Execution stopped');signal.addEventListener('abort',()=>controller.abort(),{once:true})}onEvent?.({type:'loading'});const original=p.globals.get('print');const printFn=(...args)=>onEvent?.({type:'output',value:args.map(v=>jsValue(v)).join(' ')});p.globals.set('print',printFn);try{const result=await p.runPythonAsync(makeCode(code,inputValues));if(signal?.aborted||controller.signal.aborted)throw Error('Execution stopped');let vars={};try{const raw=p.runPython('json.dumps(__bp_result, default=str)');vars=JSON.parse(raw)}catch{}onEvent?.({type:'vars',vars});onEvent?.({type:'done',state:{vars,inputs:inputValues}});return {vars,inputs:inputValues,outputs:[]}}catch(e){const msg=String(e?.message||e);if(signal?.aborted||controller.signal.aborted)throw Error('Execution stopped');throw Error(msg)}finally{p.globals.set('print',original)}}
return {run,load};
})();
const BlueprintEngine=PythonEngine;