const PythonEngine=(()=>{
let pyodide=null,loading=null;
async function load(){if(pyodide)return pyodide;if(loading)return loading;loading=(async()=>{const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/pyodide/v0.27.7/full/pyodide.js';document.head.appendChild(s);await new Promise((resolve,reject)=>{s.onload=resolve;s.onerror=()=>reject(Error('Could not load Python runtime'))});pyodide=await loadPyodide();return pyodide})();return loading}
function json(v){return JSON.stringify(v).replace(/\\/g,'\\\\').replace(/'''/g,"\\'\\'\\'")}
function makeCode(code,inputValues){const payload=json(inputValues||{});const body=code.replace(/\r/g,'').split('\n').map(line=>line.trim()?`    ${line}`:'').join('\n');return `import asyncio\nimport json\nimport math\nimport random\nimport time\n\n__bp_inputs = json.loads('''${payload}''')\n\ndef input_value(name, default=None):\n    if name not in __bp_inputs:\n        return default\n    value = __bp_inputs[name]\n    if isinstance(default, bool):\n        return str(value).strip().lower() in ('true','1','yes','on')\n    if isinstance(default, int) and not isinstance(default, bool):\n        try: return int(value)\n        except: return default\n    if isinstance(default, float):\n        try: return float(value)\n        except: return default\n    if isinstance(default, list):\n        try: return json.loads(value) if isinstance(value, str) else value\n        except: return default\n    return str(value)\n\nasync def delay(milliseconds):\n    await asyncio.sleep(max(0, float(milliseconds)) / 1000)\n\nasync def __main__():\n${body||'    pass'}\n    return {k: v for k, v in locals().items() if not k.startswith('__')}\n\n__bp_result = await __main__()\njson.dumps(__bp_result, default=str)`}
function jsValue(v){if(v===null||v===undefined)return v;if(typeof v.toJs==='function'){try{return v.toJs({dict_converter:Object.fromEntries})}catch{try{return v.toJs()}catch{return String(v)}}}return v}
async function run(code,inputValues,onEvent,signal){const p=await load();if(signal?.aborted)throw Error('Execution stopped');onEvent?.({type:'loading'});const originalPrint=p.globals.get('print');const printFn=(...args)=>onEvent?.({type:'output',value:args.map(v=>jsValue(v)).join(' ')});p.globals.set('print',printFn);try{const result=await p.runPythonAsync(makeCode(code,inputValues));if(signal?.aborted)throw Error('Execution stopped');let vars={};try{const raw=p.runPython('json.dumps(__bp_result, default=str)');vars=JSON.parse(raw)}catch{}onEvent?.({type:'vars',vars});onEvent?.({type:'done',state:{vars,inputs:inputValues}});return {vars,inputs:inputValues,outputs:[]}}catch(e){if(signal?.aborted)throw Error('Execution stopped');let msg=String(e?.message||e);msg=msg.replace(/^PythonError:\s*/,'');throw Error(msg)}finally{p.globals.set('print',originalPrint)}}
return {run,load};
})();
const BlueprintEngine=PythonEngine;